version: '3.7'
services:
    hermes:
        container_name: hermes
        build: .
        
        ports:
            - "5000:5000"
        
        volumes:
            - .:/code
        
        environment:
            FLASK_ENV: development
            SLACK_TOKEN: tuToken
